# Generated by Django 2.1.2 on 2018-12-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181206_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='分类标题')),
            ],
            options={
                'verbose_name': '攻略文章分类',
                'verbose_name_plural': '攻略文章分类',
            },
        ),
        migrations.CreateModel(
            name='StrategyArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('desc', models.CharField(default='', max_length=255, null=True, verbose_name='文章描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('read_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '攻略文章表',
                'verbose_name_plural': '攻略文章表',
            },
        ),
        migrations.AlterField(
            model_name='strategyclass',
            name='image',
            field=models.FileField(default='/media/strategy/default.png', upload_to='media/strategy/', verbose_name='缩略图'),
        ),
        migrations.AddField(
            model_name='category',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.StrategyClass', verbose_name='所属攻略'),
        ),
    ]
