# Generated by Django 2.1.2 on 2018-12-07 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181207_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '攻略对应标签',
                'verbose_name_plural': '攻略对应标签',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='strategyarticle',
            name='category',
        ),
        migrations.AlterField(
            model_name='strategyarticle',
            name='strategyClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.StrategyClass', verbose_name='所属主题'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='strategyclass',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Tag', verbose_name='标签'),
        ),
    ]
