# Generated by Django 2.1.2 on 2018-12-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181207_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '对应标签', 'verbose_name_plural': '对应标签'},
        ),
        migrations.RemoveField(
            model_name='strategyclass',
            name='tag',
        ),
        migrations.AddField(
            model_name='strategyarticle',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='所属标签'),
        ),
    ]
