# Generated by Django 2.1.2 on 2018-12-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181207_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签分类', 'verbose_name_plural': '标签分类'},
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('default', 'default'), ('primary', 'primary'), ('success', 'success'), ('info', 'info'), ('warning', 'warning'), ('danger', 'danger')], default='default', max_length=10, verbose_name='标签配色'),
        ),
    ]
